### ISSUE TITLE
Unusable Permissions when ZIPs are extracted on Linux

### ISSUE THREAD

**Issue by Sauerstoffdioxid** [Jamezo97/simplezip.js#1]
First of all, thank you very much for this library, it's exactly what I was looking for and works really well.

However, I noticed that when I extract one of the zips produced by it on my Linux based system, I get files with unusable permissions (both read and write denied for everyone). This happens because apparently the zip tools available on Linux like to save the unix file permissions into the upper two bytes of the external attributes field, and try to restore them unless the zip file comes from Windows (although I'm not quite sure how that is determined).

Currently, simplezip.js fills those two bytes with 0x0000 which leads to all permissions being denied. The closest thing to documentation of any sorts that I could find was [this post](https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute). Based on that, I have changed the line writing the external attributes field to write 0x81b40002 instead to reflect the default permissions my distribution assigns to user created files (rw-rw-r--). But I am by no means an expert when it comes to unix permissions, so I don't know if something else might be preferable.

This seems to have fixed the issue on my end. I don't know if it's the best solution to the problem as i was just looking for a workaround to get it working quickly. Another solution might be to imitate a Windows zip file, but I haven't checked out how to go about that.

**Comment by Jamezo97** [comment]
Hey Sauerstoffdioxid,

Thank you for the feedback and your research! I think I've found the root cause.

I was wary of hard-coding a file permissions, given the default permissions on my WSL2 Ubuntu instance are `-rw-r--r--` and yours are `-rw-rw-r--`, I wanted to make sure the default behaviour worked on each system.

## Extra field
At first I thought it was due to an extra field that 7-zip and other windows utilities add to their zip files.

I examined a 7-zip file and noticed that 7-zip adds an extra field to the file header in the central directory:
`0a0020000000000001001800b3778863e7b0d701b3778863e7b0d701aca3245fe7b0d701`

I managed to find some documentation on what this means, turns out it's a high precision NTFS timestamp:
https://opensource.apple.com/source/zip/zip-6/unzip/unzip/proginfo/extra.fld

I thought perhaps the extra field was being used as a hint on Linux that the file came from windows. But nope! I added this extra field and it had no effect.

I eventually tried to generate an identical ZIP file, to make sure I wasn't missing anything. 
Turns out I was missing something ;)

# Solution
The culprit was, in hindsight unsurprisingly, the 'version made by' field in the central directory header.

```js
this.buf.writeu16(0x033f); //Version made by... something?
this.buf.writeu16(0x003f); //Version made by __windows__
```

By changing to 0x003f, this seems to signify (at least to 7-zip) that the file came from the 'FAT' file system, and hence would have no permissions and that Linux should generate them.

I'll merge the changes soon :)

Cheers!

**Comment by Sauerstoffdioxid** [comment]
thank you very much for both the fix and the insights into how it works! 👍
I can confirm the issue is fixed now.
